services:

  rag-admin:
    image: 'rag-admin:latest'
    build:
      context: .
      target: runtime
    restart: "no"
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 5s
      retries: 5

  db:
    image: pgvector/pgvector:pg18-trixie
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?unset}
      - POSTGRES_USER=${POSTGRES_USER?unset}
      - POSTGRES_DB=${POSTGRES_DB?unset}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

volumes:
  app-db-data: