healthCheckTimeout: 300

models:
  "gemma3:4b-it-qat":
    cmd: |
      /app/llama-server
      --port ${PORT}
      -hf google/gemma-3-4b-it-qat-q4_0-gguf:Q4_0
      -c 32768
      -ngl 999
      --cache-type-k q8_0
      --cache-type-v q8_0
      --cache-ram 0
    ttl: 600

  "qwen3-embedding-0.6b":
    cmd: |
      /app/llama-server
      --port ${PORT}
      -hf Qwen/Qwen3-Embedding-0.6B-GGUF:Q8_0
      --embedding
      --pooling mean
      -c 8192
      -ngl 999
      --cache-ram 0
    ttl: 600

  "qwen3-reranker-0.6b":
    cmd: |
      /app/llama-server
      --port ${PORT}
      -hf mradermacher/Qwen3-Reranker-0.6B-GGUF:Q8_0
      --reranking
      --pooling rank
      -c 8192
      -ngl 999
      --cache-type-k q8_0
      --cache-type-v q8_0
      --cache-ram 0
    ttl: 600
